#!/bin/bash

### BEGIN INIT INFO
# Provides:          personnal_nextcloud
# Required-Start:    $network $remote_fs docker
# Required-Stop:     $network $remote_fs docker
# Should-Start:      $time
# Should-Stop:       $time
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Gestionnaire de conteneurs Docker pour Nextcloud
# Description:       Script de gestion des conteneurs Docker pour Nextcloud et Portainer.
#                    Permet de démarrer, arrêter, redémarrer et surveiller les services
#                    cloud personnels de manière automatisée.
### END INIT INFO


action=$1
current_path=$(pwd)

case "$action" in
    "restart" )
        echo "restart all cloud container"
        cd $current_path/docker &&  docker compose -f docker-compose.yml build && docker compose -f docker-compose.yml up -d
        cd $current_path/common/portainer &&  docker compose -f docker-compose.yml build && docker compose -f docker-compose.yml up -d
        docker ps
    ;;
    "start" )
        echo "start all cloud container"
        docker network create personnal_nextcloud
        cd $current_path/docker &&  docker compose -f docker-compose.yml build && docker compose -f docker-compose.yml up -d
        cd $current_path/common/portainer &&  docker compose -f docker-compose.yml build && docker compose -f docker-compose.yml up -d
        docker ps
        ;;
    "stop" )
        echo "Stop all cloud container"
        cd $current_path/docker && docker compose -f docker-compose.yml down
        cd $current_path/common/portainer && docker compose -f docker-compose.yml down
        docker network rm personnal_nextcloud
        docker ps
        ;;
    * )
        echo "Usage : /etc/init.d/cloud_containers.sh restart|start|stop"
        ;;
esac

exit 0